services:
  app:
    container_name: game_app
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    command: npm start
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}
      - SOLANA_RPC_HTTPS=${SOLANA_RPC_HTTPS}
      - SOLANA_RPC_WSS=${SOLANA_RPC_WSS}
      - VAULT_PRIVATE_KEY=${VAULT_PRIVATE_KEY}
      - PYTH_PROGRAM_ID=${PYTH_PROGRAM_ID}
      - MASTER_MNEMONIC=${MASTER_MNEMONIC}
      - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
      - TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}
      - TWITTER_CALLBACK_URL_BASE=${TWITTER_CALLBACK_URL_BASE}
      - TWITTER_REDIRECT_AFTER_LOGIN=${TWITTER_REDIRECT_AFTER_LOGIN}
      - SESSION_ENCRYPTION_KEY=${SESSION_ENCRYPTION_KEY}
      - SESSION_EXPIRE_AFTER_SECONDS=${SESSION_EXPIRE_AFTER_SECONDS}
      - FRONTEND_URL=${FRONTEND_URL}
      - SETTLE_AUTH_KEY=${SETTLE_AUTH_KEY}
