services:
  app:
    container_name: game_app
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    command: npm start
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}
      - SOLANA_RPC_HTTPS=${SOLANA_RPC_HTTPS}
      - SOLANA_RPC_WSS=${SOLANA_RPC_WSS}
      - VAULT_PRIVATE_KEY=${VAULT_PRIVATE_KEY}
      - PYTH_PROGRAM_ID=${PYTH_PROGRAM_ID}
